version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db-bss
    ports:
      - "1521:1521"
      - "5500:5500"  # EM Express
    environment:
      ORACLE_PASSWORD: Oracle123
      APP_USER: bss_user
      APP_USER_PASSWORD: bss_pass_2024
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - bss-network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  bss-api:
    build: .
    container_name: bss-api
    ports:
      - "8080:8080"  # Mudamos para 8080 (padrão)
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db-bss:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: bss_user
      SPRING_DATASOURCE_PASSWORD: bss_pass_2024
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: myjwtsecretkeymyjwtsecretkeymyjwtsecretkeymyjwtsecretkey
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - bss-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  oracle-data:

networks:
  bss-network:
    driver: bridge