-- V1__init.sql
-- Usuários da plataforma
CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    email VARCHAR2(100),
    tipo VARCHAR2(20)
);

-- Login
CREATE TABLE login (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id),
    username VARCHAR2(50) UNIQUE,
    senha VARCHAR2(100)
);

-- Equipamentos monitorados
CREATE TABLE equipamento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id),
    nome VARCHAR2(100),
    localizacao VARCHAR2(100),
    status VARCHAR2(20)
);

-- Leitura de consumo de energia
CREATE TABLE consumo_energia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipamento NUMBER REFERENCES equipamento(id),
    leitura_kwh NUMBER(10,2),
    data_leitura TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Alertas de consumo
CREATE TABLE alerta_consumo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipamento NUMBER REFERENCES equipamento(id),
    consumo_kwh NUMBER(10,2),
    status VARCHAR2(20) DEFAULT 'pendente',
    data_alerta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Log de eventos
CREATE TABLE log_sistema (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem VARCHAR2(255),
    data_evento TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Inserção de dados de exemplo
INSERT INTO usuario (nome, email, tipo) VALUES ('João Silva', 'joao@bss.com', 'morador');
INSERT INTO usuario (nome, email, tipo) VALUES ('Maria Souza', 'maria@bss.com', 'investidor');
INSERT INTO usuario (nome, email, tipo) VALUES ('Carlos Lima', 'carlos@bss.com', 'construtora');
INSERT INTO usuario (nome, email, tipo) VALUES ('Ana Dias', 'ana@bss.com', 'fornecedor');
INSERT INTO usuario (nome, email, tipo) VALUES ('Bruno Rocha', 'bruno@bss.com', 'morador');

INSERT INTO login (id_usuario, username, senha) VALUES (1, 'joaos', 'senha123');
INSERT INTO login (id_usuario, username, senha) VALUES (2, 'marias', 'senha123');
INSERT INTO login (id_usuario, username, senha) VALUES (3, 'carlosl', 'senha123');
INSERT INTO login (id_usuario, username, senha) VALUES (4, 'anad', 'senha123');
INSERT INTO login (id_usuario, username, senha) VALUES (5, 'brunor', 'senha123');

INSERT INTO equipamento (id_usuario, nome, localizacao, status) VALUES (1, 'Sensor Solar', 'Cobertura', 'ativo');
INSERT INTO equipamento (id_usuario, nome, localizacao, status) VALUES (1, 'Ar condicionado', 'Sala 1', 'ativo');
INSERT INTO equipamento (id_usuario, nome, localizacao, status) VALUES (1, 'Ar condicionado', 'Salão de Festas', 'ativo');
INSERT INTO equipamento (id_usuario, nome, localizacao, status) VALUES (2, 'Luminária LED', 'Garagem', 'ativo');
INSERT INTO equipamento (id_usuario, nome, localizacao, status) VALUES (2, 'Sensor Presença', 'Corredor Torre 1', 'ativo');

INSERT INTO consumo_energia (id_equipamento, leitura_kwh, data_leitura) VALUES (1, 120.5, SYSTIMESTAMP - INTERVAL '5' DAY);
INSERT INTO consumo_energia (id_equipamento, leitura_kwh, data_leitura) VALUES (2, 85.0, SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO consumo_energia (id_equipamento, leitura_kwh, data_leitura) VALUES (3, 40.2, SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO consumo_energia (id_equipamento, leitura_kwh, data_leitura) VALUES (4, 95.7, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO consumo_energia (id_equipamento, leitura_kwh, data_leitura) VALUES (1, 130.8, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO alerta_consumo (id_equipamento, consumo_kwh, status, data_alerta) VALUES (1, 120.5, 'pendente', SYSTIMESTAMP - INTERVAL '5' DAY);
INSERT INTO alerta_consumo (id_equipamento, consumo_kwh, status, data_alerta) VALUES (2, 85.0, 'resolvido', SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO alerta_consumo (id_equipamento, consumo_kwh, status, data_alerta) VALUES (3, 40.2, 'pendente', SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO alerta_consumo (id_equipamento, consumo_kwh, status, data_alerta) VALUES (4, 95.7, 'pendente', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO alerta_consumo (id_equipamento, consumo_kwh, status, data_alerta) VALUES (1, 130.8, 'pendente', SYSTIMESTAMP - INTERVAL '1' DAY);
